# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: publication/
    weight: 11
  - name: 元字
    url: /yuanzi/
    weight: 12
  - name: Gorillaz
    url: /gorillaz/
    weight: 13
  - name: Mol sounds
    url: /mol-sounds/
    weight: 14
  # - name: Talks
  #   url: talks/
  #   weight: 12
